### ISSUE TITLE
Misreported error: watcher/finder inconsistency

### ISSUE THREAD

**Issue by skeggse** [StreakYC/page-parser-tree#2]
I've been digging into an issue where I see the `watcher found element already found by finder` error. It looks like it's as a result of creating a watcher that has two `sources`, and a `$map`, where the `sources` have an ancestor <-> descendant relationship, and the `$map` produces the same element for both.

The `watcherFinderMerger` utility assumes that if the `watcherSet` produces a value, and it already exists in the `currentElements` `Set`, that it was produced by a finder. This is not the case, as it was produced twice by the same watcher.

I'm not sure what part of the overall architecture is at fault here - I can see a controller's `add` function getting called twice from `live-set`, but I suspect that's the correct behavior. The `live-set` itself doesn't catch this duplication because while the element is unique, its containing object is the object [here](https://github.com/StreakYC/page-parser-tree/blob/04fdf9b8442831e981b38f368ecc02a1dd3c3cc7/src/createTransformer/index.js#L46).

I'd like to put together a proper repro case for this, but I don't have a good system for quickly spinning up an environment to test npm modules client-side in (if you have suggestions for this, I'm happy to hear them :D).

**Comment by skeggse** [comment]
oops sorry, hit enter too soon (editing)

**Comment by skeggse** [comment]
edited

**Comment by AgentME** [comment]
Yeah, if you have any watcher step that could have the same element twice, then things can go wrong currently. The behavior around duplicate elements in LiveSets in currently left somewhat undefined. Adding an element a second time to a LiveSet currently emits an 'add' event which it shouldn't.

Fixing that will fix the specific error you're seeing, but the result will still contain some surprising behavior: if the element is present in both of the sources and is then removed from one of the sources, then it will be removed from the output. It's possible to fix that and remove the limitation around duplicate elements, but I'm not sure about the performance of doing that. If there's a performance hit, then it should be opted into. Though I've only ever had duplicate elements accidentally and never intentionally, which leads me to thinking that all that should be done is get some error logging in place to warn users who have duplicate elements in any step of their watcher pipeline.

**Comment by AgentME** [comment]
>Adding an element a second time to a LiveSet currently emits an 'add' event which it shouldn't.

(Never mind, I was wrong about that part. LiveSet already correctly handles that case.)

**Comment by skeggse** [comment]
> Adding an element a second time to a LiveSet currently emits an 'add' event which it shouldn't.

It looks like that isn't a problem with LiveSet itself, as it [checks for the added element](https://github.com/StreakYC/live-set/blob/master/src/index.js#L284), but rather with how page-parser-tree (or maybe tag-tree) structures the data it stores in the LiveSet.

>If there's a performance hit, then it should be opted into.

I wonder if there'd be a way to specify a deduplication "rule" where I signal that I _know_ there will be duplicate elements produced, and want them to be appropriately tracked as such.

**Comment by AgentME** [comment]
I think I get it more now: you have something like this:

```js
const page = new PageParserTree(document, {
  tags: {},
  watchers: [
    // ...
    {sources: ['foo1', 'foo2'], tag: 'bar', selectors: [
      'div.bar'
    ]},
  ]
};
```

One problem is that tagged items aren't just elements, but also some context of where the element came from including a list of its parent tags, which is important when you are using the tag "ownedBy" feature. If you have a specific element tagged as foo1 with some specific parent tags, and you later get the same element tagged as foo2 with a different set of parent tags, if you de-dupe based on elements, then the application will never get information about foo2's parents, and if the element is removed from the foo1 set, then it will either have to awkwardly persist with an outdated context that may not be consistent with the DOM and the TagTree. If you want to de-dupe on elements, then the sane thing to do seems to be to require throwing away the parent/context information. This could be an option in the Watcher object.

(Another option would be to instantiate the watcher pipeline once for each source, so that you get the same element tagged as bar twice, each with a different parent context. I'd be surprised if there was any demand for this, but it could always be a separate option.)

**Comment by skeggse** [comment]
Yeah I can see this issue gets complicated. I've worked around the issue for the time being by making `foo1` and `foo2` strictly mutually exclusive, at the cost of additional an additional watcher to correctly narrow the matched nodes of another tag.
